---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-secret
  namespace: scriptscribe
spec:
  encryptedData:
    JWT_SECRET: AgC2kgjhqRRwY0ukJEBUWd3kWCNV8CZ7EebsF6lbBsRn1P4HkyKYmgOg4/7IRznKwM5w9d8+w+9R3OV5MpLeQJ5ImCbi+MWhuNmIISB4ymu0lKgXRz1Gme1gI9MJPifXGnIZccD7s+x/Qao3kqEaFp7zgNCxk0jetw9KgpWKS0hhsv0RBD+uNo9h6ae/2SbEI1WIUt/OGI2SBm5ZbhK0NPZX6pH9Ze/DJVsCx1OMJff+zlh1lxWxvW/68qbngvpIf0pDk954olzUF722k7ZkTm6Q39FJkHqE4oST8/5lBhtqBh/8OC0oJ3BZ8Ktroc8UWihHqVI7qpjRbO8NXqLvtPGKOF7i81+AQiilYrcqVKY4W3o7f4UWtFuUx1hv/g7R2lMr6vO8Mcij/DRnJukFYEUy1H57ElVgBEsCETJHukg8bL9FfMVd7OkiKW3BMtzDxsbobijMIlV5OM/SYEr5JaG2cWzYkUm226o5u8Mthu4GLIPaZYwXgbIKqVj5JEIzXkdXYs8eHDGiWqHHjAzlswIs4152Chec9tWg2/3dilS6sxGTTP5xn5rJ7q+Oc4o40clxewWMwhyEz4gfByYOoN7j8nIz3NajYXwr1y7AHi31t98GvDePqKMbGEj8RV5rE4Ig/0EibL/ZxVWn8krT3ajrb/UuoXoRcgvq6YEW8GHqEzyuJt/4YK02kft/AKLIT1hscAiv7vIJTs+KMz965k13UmaN/j59ekhJdC47WIepQBc=
    PASS_SALT: AgCtxnpAhu5qyijwBarfp5OVGKOeH5BRjf1ybzPLWcTbuQXCcU/fYqoNZnK5qpoWfxTKT+r1DXayxcMTcosG6OofMel3lwGBVuXNtZHUe6er7qAOIwPn2DqeoBqx6bBoMqNsM5wTRqFzPAEji0ZybpwN343FloECQA0PRLDxTya8Qs8r145ZHuasH+cV0cHApv6ke+PRmdrrMBOkLInLesp9fkz13gPzbx1jTDmx7RRdPjPBckUqAPDxrTU+Q5xxnXs3AjRWVWuk1m8kOwfuOnTTf5HmXeCxjLjFkNyBy/VOIHsistVqBrxIXaXIujy1dZEau5raAkBMc02yr3cBJ/JeKTcSF1+ZsrZPpws6OxuVTNoUa3MplMLVHSHBldHEjrtHk9+IPav+KTXgQmtg8PSrbi9iwvp3HsmIfyvWrJgf3UxJqXCN93ky3bpemF4e9VAmhBPKIXxAeUjDPd1Y0mBG825bP0oT7TJEcNfXQnOdR39Pg5+50d0dA41YI734nL23tuZyK4LjAOHoFUIU2MDfkl6ht99nYo4KUWeF+B2LM9jBNCI8hxem1fcjFqWirQUt8snHw3SUAlxAcPCQrec6DgdBTzLr/WTdh2jPVYSuU+n6MOFAcee2w6evBO8/sy0FU7Ikh0B4ma58UY9Zdf2Vq608WgRNGlI7m2tF2tzUd9Jlw96/VwjbMKPYqApRX2ilUg6y+KnfxbdNcre4JdI7tBPOpaJz4JROB8gJjjEdb4c=
  template:
    metadata:
      name: auth-secret
      namespace: scriptscribe
