apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    spec:
      containers:
        - name: frontend
          image: ghcr.io/whyredfire/ss-frontend:b5d04ef36e5954f5b40e93b1886b96869c305296
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
