name: Build and Push to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta for frontend
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/whyredfire/ss-frontend

      - name: Build and Push Docker Image for frontend
        uses: docker/build-push-action@v6
        with:
          context: frontend
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta-frontend.outputs.tags }}
          labels: ${{ steps.meta-frontend.outputs.tags }}
          cache-from: type=registry,ref=ghcr.io/whyredfire/ss-frontend:buildcache
          cache-to: type=registry,ref=ghcr.io/whyredfire/ss-frontend:buildcache,mode=max

      - name: Docker meta for backend
        id: meta-backend
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/whyredfire/ss-backend

      - name: Build and Push Docker Image for backend
        uses: docker/build-push-action@v6
        with:
          context: backend
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta-backend.outputs.tags }}
          labels: ${{ steps.meta-fastapi.outputs.tags }}
          cache-from: type=registry,ref=ghcr.io/whyredfire/ss-backend:buildcache
          cache-to: type=registry,ref=ghcr.io/whyredfire/ss-backend:buildcache,mode=max
