name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/docker-build.yaml
      - backend/**/*
      - frontend/**/*
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        arch: [amd64, arm64]
        service: [frontend, backend]
        include:
          - arch: amd64
            runner: ubuntu-latest
          - arch: arm64
            runner: ubuntu-24.04-arm

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build Docker Image for ${{ matrix.service }}
        uses: docker/build-push-action@v7
        with:
          context: ${{ matrix.service }}
          load: true
          tags: ghcr.io/whyredfire/ss-${{ matrix.service }}:${{ github.sha }}-${{ matrix.arch }}
          cache-from: type=gha,scope=${{ github.ref_name }}-${{ matrix.service }}-${{ matrix.arch }}
          cache-to: type=gha,mode=max,scope=${{ github.ref_name }}-${{ matrix.service }}-${{ matrix.arch }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: "ghcr.io/whyredfire/ss-${{ matrix.service }}:${{ github.sha }}-${{ matrix.arch }}"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"

      - name: Push Docker Image to GHCR
        run: |
          docker push ghcr.io/whyredfire/ss-${{ matrix.service }}:${{ github.sha }}-${{ matrix.arch }}

  create-multiarch:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Create multi-arch manifests
        run: |
          services=("ss-frontend" "ss-backend")

          for service in "${services[@]}"; do
            echo "Creating manifest for $service..."

            docker buildx imagetools create \
              -t ghcr.io/whyredfire/$service:latest \
              -t ghcr.io/whyredfire/$service:${{ github.sha }} \
              ghcr.io/whyredfire/$service:${{ github.sha }}-amd64 \
              ghcr.io/whyredfire/$service:${{ github.sha }}-arm64
          done

      - name: Update image tags
        run: |
          yq -i ".spec.template.spec.containers[0].image = \"ghcr.io/whyredfire/ss-frontend:${GITHUB_SHA}\"" k8s/frontend/deployment.yaml
          yq -i ".spec.template.spec.containers[0].image = \"ghcr.io/whyredfire/ss-backend:${GITHUB_SHA}\"" k8s/backend/deployment.yaml

      - name: Commit to repo
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          commit_message: "k8s: Bump images to ${{ github.sha }} [no ci]"
          file_pattern: "k8s/**/deployment.yaml"
